// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZoXxvlEXImSHeYFh4kfawCNZGPw35ExE',
    appId: '1:867220584701:web:071c50d1c149a4241ba694',
    messagingSenderId: '867220584701',
    projectId: 'sd9550-firestore-16432',
    authDomain: 'sd9550-firestore-16432.firebaseapp.com',
    storageBucket: 'sd9550-firestore-16432.firebasestorage.app',
    measurementId: 'G-EDHF3K7BG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJqkbh3jeOcFEnP6AoHIzYWEA0nDFG8GI',
    appId: '1:867220584701:android:83b07424feffcaec1ba694',
    messagingSenderId: '867220584701',
    projectId: 'sd9550-firestore-16432',
    storageBucket: 'sd9550-firestore-16432.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZoXxvlEXImSHeYFh4kfawCNZGPw35ExE',
    appId: '1:867220584701:web:206e01a506d9f63d1ba694',
    messagingSenderId: '867220584701',
    projectId: 'sd9550-firestore-16432',
    authDomain: 'sd9550-firestore-16432.firebaseapp.com',
    storageBucket: 'sd9550-firestore-16432.firebasestorage.app',
    measurementId: 'G-B8MSVRYRLZ',
  );
}
