// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCklJA0TJCCSRq8AtkArqwEfGNylMTHjjs',
    appId: '1:773125554272:web:f4be11c2ce222f18bb4305',
    messagingSenderId: '773125554272',
    projectId: 'sd9550-firebase',
    authDomain: 'sd9550-firebase.firebaseapp.com',
    storageBucket: 'sd9550-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2tK73e1Sw_5cnOW5XaMYJFfwqXPVzBc',
    appId: '1:773125554272:android:1b8c3f3c32652fbcbb4305',
    messagingSenderId: '773125554272',
    projectId: 'sd9550-firebase',
    storageBucket: 'sd9550-firebase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCklJA0TJCCSRq8AtkArqwEfGNylMTHjjs',
    appId: '1:773125554272:web:8f154f8818ffbcfcbb4305',
    messagingSenderId: '773125554272',
    projectId: 'sd9550-firebase',
    authDomain: 'sd9550-firebase.firebaseapp.com',
    storageBucket: 'sd9550-firebase.firebasestorage.app',
  );

}